config/routes.rb
Rails.application.routes.draw do

  get 'votes/create'

  get 'votes/update'

  get 'votes/destroy'

  get 'votes/show'

  get 'votes/index'

  get 'votes/new'

  get "comments/comment_history"

  devise_for :users

  concern :commentable do
    resources :comments
  end

  concern :votable do
    resources :votes
  end
  resources :questions, concerns: :commentable do

    resources :answers, concerns: :commentable
  end

  root 'questions#index'

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  has_many :answered_users, source: :user, through: :answers
  has_many :comments, as: :commentable
  has_many :votes, as: :votable
  validates :content, :presence => true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
before_action :authenticate_user!, only: [:new]
 before_action :set_question, only: [:show, :update, :destroy, :edit]
#before_action :check_authorized_user, except: [:index, :show]


 def index
    @questions = Question.all
 end

 def show
  @answers = @question.answers
  @comments = @question.comments

  #@commentable = @answer.commentable
 end

 def new
    @question = current_user.questions.new
 end
 def edit
 end


 def create
    @question = current_user.questions.new(question_params)
    respond_to do |format|
      if @question.save
        format.html { redirect_to questions_path, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: questions_path }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to questions_path, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: questions_path }
      else
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end
    #def check_authorized_user
      #@question
    #end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:content)
    end

end

app/helpers/question_helper.rb
module QuestionHelper
  def question_error_messages!
    return '' if @question.errors.empty?
    flash.now[:error] = @question.errors.full_messages.map { |msg| "#{msg}." }[0]
  end
end

app/views/questions/_form.html.haml
.col-lg-3
.col-lg-6
  = form_for(@question) do |f|
    - question_error_messages!
    .field
      = f.label :question
      %br/
      = f.text_area :content, cols: "60", rows: "10"
      %br/
    .actions
      = f.submit "Create Question", :class => "btn btn-primary"
      = link_to 'Show', @question
      = link_to 'Back', root_path
.col-lg-3

app/views/questions/edit.html.haml
.center
  %h1 Editing Post
= render 'form'
/puts "abii"

app/views/questions/index.html.haml
%table
  %tbody
    - @questions.each do |question|
      %tr
      %td= link_to question.content, question
      - if current_user == question.user
        %td= button_to 'Edit', edit_question_path(question), class: "btn btn-primary btn-xs"
        %td= button_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary btn-xs"
%br/

app/views/questions/new.html.haml
.center
  %h1 New questions
%span= render 'form'

app/views/questions/show.html.haml
%h1
  %span= @question.content
  %span.Firstname= "-"
  %span.reviewer= current_user.Firstname
  %span.reviewer= current_user.lastname
%hr
%h4.questioncomment
  = render :partial => 'comments/index', :locals => { comments: @comments, question: @question}
= link_to "Add comment", new_question_comment_path(@question), method: :get
%br
%br
%span= @question.answers.count
%span= @question.user.anscount
%span= link_to "Add answer", new_question_answer_path(@question), method: :get
= render :partial => 'answers/index', :locals => { answers: @answers, question: @question}