config/routes.rb
Rails.application.routes.draw do

  get 'votes/create'

  get 'votes/update'

  get 'votes/destroy'

  get 'votes/show'

  get 'votes/index'

  get 'votes/new'

  get "comments/comment_history"

  devise_for :users

  concern :commentable do
    resources :comments
  end

  concern :votable do
    resources :votes
  end
  resources :questions, concerns: :commentable do

    resources :answers, concerns: :commentable
  end

  root 'questions#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  validates :comment, :presence => true

 def check_history?
   self.history_id.blank?
 end

 def self.show_history(num)
   where("history_id IS NULL AND id =? OR history_id =? AND id != ?", num, num, num).order("id DESC").first
 end

 def self.list_comment_history(num,not_num)
   where("history_id IS NULL AND id =? XOR history_id =? AND id != ? AND id != ?",num,num,num, not_num).order("id DESC")
 end

end
  #validates :user_id, :uniqueness => { :scope => :question_id, :message => "You have authority to write one comment only"}

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_comment, only:[:show, :edit, :update, :destroy]
  before_action :find_question, only:[:show, :edit, :update, :destroy, :create, :new]

  def create
    commentable= find_commentable
    @commentable= commentable.comments.new(comment_params)
    @commentable.user = current_user
    if @commentable.save(comment_params)
      if (@commentable.commentable_type == 'Question')
        redirect_to @question, notice: 'question comment was successfully created.'
      else
        redirect_to @question, notice: 'Answer comment was successfully created.'
      end
    else
      render :new
    end
  end


  def edit
  end

  def destroy
    #find_question
    #@commentable = @question.comments.where(:id => params[:id]).first
    @commentable.destroy
    if (@commentable.commentable_type == 'Question')
      redirect_to @question, notice: 'question comment was successfully destroyed.'
    else
      redirect_to @question, notice: 'Answer comment was successfully destroyed.'
    end
  end


  def update
    commentable = find_commentable
    if @commentable.check_history?
     p true
     params = comment_params.merge(history_id: @commentable.id)
     @commentable = commentable.comments.new(params)
     @commentable.user = current_user
     @commentable.save
    else
     p false
     params = comment_params.merge(history_id: @commentable.history_id)
     @commentable = commentable.comments.new(params)
     @commentable.user = current_user
     @commentable.save

   end

   if(@commentable.commentable_type == "Question")

     redirect_to @question, notice: 'Question_Comment was successfully updated.'
   else
      # @commentable.update(comment_params)
     redirect_to @question, notice: 'Answer_Comment was successfully updated.'
   end
 end
  def comment_history
    # p "params======$#{params}"
    # p "params[:history_id]====#{params[:history_id]}"
    @comment_history = Comment.list_comment_history(params[:history_id], params[:dont_show])
    # p "@comment_history=====#{@comment_history.inspect}"
   # Comment.where("history_id IS NULL AND id =? XOR history_id =? AND id != ?", 143,143, 143).order("id DESC").first
  end


  # def update
  #   find_question
  #   #@commentable = @question.comments.where(:id => params[:id]).first
  #   @commentable.update(comment_params)
  #   if (@commentable.commentable_type == 'Question')
  #     redirect_to @question, notice: 'question comment was successfully updated.'
  #   else
  #     redirect_to @question, notice: 'Answer comment was successfully updated.'
  #   end
  # end



  def show
  end

  def index
    @comments = Comment.all
  end

  def new
    commentable= find_commentable
    @commentable= commentable.comments.new
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def find_commentable
     if params[:question_id] && params[:answer_id]
       klass = "answers"
       id = params[:answer_id]
     else
       klass = "questions"
       id = params[:question_id]
     end
     return "#{klass}".singularize.classify.constantize.find(id)
  end
  def set_comment
    @commentable = Comment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:comment)
  end

  def find_question
    @question = Question.find params[:question_id]
  end


end

app/helpers/comments_helper.rb
module CommentsHelper
  def comment_error_messages!
    return '' if @commentable.errors.empty?
    flash.now[:error] = @commentable.errors.full_messages.map { |msg| "#{msg}." }[0]
  end
end

app/views/comments/_form.html.haml
.col-lg-3
.col-lg-6
  = form_for([@question, @commentable]) do |f|
    - comment_error_messages!
    .formgroup
      = f.label :comments
      %br/
      = f.text_area :comment, cols: "60", rows: "10"
      %br/
      - if params[:answer_id].present?
        = hidden_field_tag :answer_id, params[:answer_id]
    .actions
      = f.submit "Update Comment", :class => "btn btn-primary"
.col-lg-3

app/views/comments/_index.html.haml
.question_comment
  - question.comments.where("history_id IS NULL").each do |comment|
    - question_comment = Comment.show_history(comment.id)
    %span= question_comment.comment
    %span.Firstname="-"
    %span= current_user.Firstname
    %span= current_user.lastname
    - if current_user == question_comment.user
      %span.Firstname= link_to 'Edit', edit_question_comment_path(id: comment.id, question_id:question)
      - unless question_comment.check_history?
        %span.Firstname= link_to 'Edited',  comments_comment_history_path(history_id: question_comment.history_id, dont_show: question_comment.id)


      %span.Firstname= link_to 'Destroy', question_comment_path(id: comment.id, question_id:question), method: :delete, data: { confirm: 'Are you sure?' }
    %br/
    %br/

app/views/comments/comment_history.html.haml
.answer_comment
  - @comment_history.each do |comment|
    %span= comment.comment
    %span.Firstname="-"
    %span= current_user.Firstname
    %span= current_user.lastname
    %br/
    %br/

app/views/comments/edit.html.haml
.center
  %h1 Editing Comment
= render :partial => 'form', :locals => {comment: @comment, question: @question}

app/views/comments/new.html.haml
.center
  %h1 Adding comments
= render :partial => 'form', :locals => { comment: @comment, question: @question }