config/routes.rb
Rails.application.routes.draw do

  get 'votes/create'

  get 'votes/update'

  get 'votes/destroy'

  get 'votes/show'

  get 'votes/index'

  get 'votes/new'

  get "comments/comment_history"

  devise_for :users

  concern :commentable do
    resources :comments
  end

  concern :votable do
    resources :votes
  end
  resources :questions, concerns: :commentable do

    resources :answers, concerns: :commentable
  end

  root 'questions#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  has_many :comments, as: :commentable
  has_many :votes, as: :votable
  validates :answer, :presence => true
  validates :user_id, :uniqueness => { :scope => :question_id, :message => "You have authority to write one answer only"}
def check_history?
 self.history_id.blank?
end

def self.show_history(num)
 where("history_id IS NULL AND id =? OR history_id =? AND id != ?", num, num, num).order("id DESC").first
end

def self.list_comment_history(num,not_num)
 where("history_id IS NULL AND id =? XOR history_id =? AND id != ? AND id != ?",num,num,num, not_num).order("id DESC")
end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  before_action only: [:new, :create]

  def create
    find_question
    @answer = @question.answers.build(answer_params.merge({user_id: @question.user_id}))
    if @answer.save
      redirect_to question_path(@question), notice: 'answer was successfully created.'
    else
      render :new
    end
  end


  def edit
    find_question
    @answer = @question.answers.where(:id => params[:id]).first
  end

  def destroy
    find_question
    @answer = @question.answers.where(:id => params[:id]).first
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to @question, notice: 'answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update
    find_question
    @answer = @question.answers.where(:id => params[:id]).first
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to  @question, notice: 'answer was successfully updated.' }
        format.json { render :show, status: :ok, location:  @question }
      else
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    find_question
    @answer = @question.answers.find(params[:id])
  end

  def index
    @answers = Answer.all
  end

  def new
    find_question
    @answer = @question.answers.build
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_answer
    @answer = answer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def answer_params
    params.require(:answer).permit(:answer)
  end

  def find_question
    @question = Question.find params[:question_id]
  end


end

app/helpers/answers_helper.rb
module AnswersHelper
  def answer_error_messages!
    return '' if @answer.errors.empty?
    flash.now[:error] = @answer.errors.full_messages.map { |msg| "#{msg}." }[0]
  end
end

app/views/answers/_form.html.haml
.col-lg-3
.col-lg-6
  = form_for([@question, @answer]) do |f|
    - answer_error_messages!
    .field
      = f.label :answers
      %br/
      = f.text_area :answer, cols: "60", rows: "10"
      %br/
    .actions
      = f.submit "Create Answer", :class => "btn btn-primary"
      = link_to 'Back', root_path
.col-lg-3

app/views/answers/_index.html.haml
- question.answers.each do |answer|
  .question_answer
    %br
    %span= answer.answer
    %span.Firstname="-"
    %span= answer.user.Firstname
    %span= answer.user.lastname
    - if current_user == answer.user
      %span.answer_edit= link_to 'Edit', edit_question_answer_path(id: answer.id, question_id: question.id)
      %span.answer_destroy= link_to 'Destroy', question_answer_path(id: answer.id, question_id: question.id), method: :delete, data: { confirm: 'Are you sure?' }

    %br/
  - answer.comments.where("history_id IS NULL").each do|c|
    - answer_comment = Comment.show_history(c.id)
    .answer_comment
      %hr
      %span= answer_comment.comment
      %span.Firstname="-"
      %span= current_user.Firstname
      %span= current_user.lastname
      - if current_user == answer_comment.user
        %span.answer_comment_edit= link_to 'Edit', edit_question_answer_comment_path(id: c.id, answer_id: answer.id, question_id:question)
        - unless answer_comment.check_history?
          %span.Firstname= link_to 'Edited',  comments_comment_history_path(history_id: answer_comment.history_id, dont_show: answer_comment.id)
        %span.answer_comment_destroy= link_to 'Destroy', question_comment_path(id: c.id, question_id:question), method: :delete, data: { confirm: 'Are you sure?' }
        %hr
  %span.answer_comment_button= link_to "Answer comment", new_question_answer_comment_path(question, answer_id: answer.id)

app/views/answers/destroy.html.haml
<h1>Answers#destroy</h1>
<p>Find me in app/views/answers/destroy.html.erb</p>

app/views/answers/edit.html.haml
.center
  %h1 Editing Post
= render :partial => 'form', :locals => {answer: @answer, question: @question}

app/views/answers/new.html.haml
.center
  %h1 Adding answer
= render :partial => 'form', :locals => { answer: @answer, question: @question }

app/views/answers/show.html.haml
= @answer.answer
= link_to "Add comment", new_question_answer_comment_path(@question,@answer), method: :get

app/views/answers/update.html.haml
.center
  %h1 Answers#update
%p Find me in app/views/answers/update.html.erb