config/routes.rb
Rails.application.routes.draw do

  get 'votes/create'

  get 'votes/update'

  get 'votes/destroy'

  get 'votes/show'

  get 'votes/index'

  get 'votes/new'

  get "comments/comment_history"

  devise_for :users

  concern :commentable do
    resources :comments
  end

  concern :votable do
    resources :votes
  end
  resources :questions, concerns: :commentable do

    resources :answers, concerns: :commentable
  end

  root 'questions#index'

end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Firsttask"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    / For third-generation iPad with high-resolution Retina display:
    / Size should be 144 x 144 pixels
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    / For iPhone with high-resolution Retina display:
    / Size should be 114 x 114 pixels
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    / For first- and second-generation iPad:
    / Size should be 72 x 72 pixels
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    / For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
    / Size should be 57 x 57 pixels
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    / For all other devices
    / Size should be 32 x 32 pixels
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
  %body
    .wrapper
      %nav.navbar.navbar-default
        .container
          / Brand and toggle get grouped for better mobile display
          .navbar-header
            %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            %a.navbar-brand{:href => "#"} Firsttask
          / Collect the nav links, forms, and other content for toggling
          #bs-example-navbar-collapse-1.collapse.navbar-collapse
            %ul.nav.navbar-nav
              %li.dropdown
                %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                  Questions
                  %span.caret
                %ul.dropdown-menu
                  %li
                    =link_to "All Question", root_path
                  %li
                    =link_to "Create Question", new_question_path
            %ul.nav.navbar-nav.navbar-right{class: user_signed_in? ? "signed-in-navbar" : "" }
              - unless user_signed_in?
                %li
                  = link_to "Sign In",new_user_session_path
                %li
                  = link_to "Sign Up",new_user_registration_path
              - else
                %li.dropdown
                  %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                    = image_tag(current_user.avatar.thumb.url)
                    = current_user.Firstname
                    %span.caret
                  %ul.dropdown-menu
                    %li
                      = link_to "Edit User",edit_user_registration_path
                    %li
                      = link_to "sign out",destroy_user_session_path,method: :delete
      .container
        .row
          = bootstrap_flash
          = yield

      .push
    %footer
      .container
      %center @company 2016
    / /container